### ISSUE TITLE
Will jSignature work with a signature pad device connected to a PC?

### ISSUE THREAD

**Issue by steepleman86** [willowsystems/jSignature#10]
Did not find any information that covers this topic.  Mousing is not that easy to use for signature.  Having it work with a signature pad would make it a whole lot easier (when working with an iPad).  If this did work it would expand the list of device configurations where this code could be used.

**Comment by dvdotsenko** [comment]
@steepleman86 

Not sure I understand the issue question. This widget works everywhere where there is a standard browser, including tablets and phones (Android, iOS etc.)

Take a look at the screenshot on the home page:

http://willowsystems.github.com/jSignature/

Is there some tablet that you tried and saw jSignature not working?

**Comment by steepleman86** [comment]
We are looking at developing a website that will allow people to capture signatures.  The platform this website will be accessed from will vary from a tablet to a PC.  If we use a tablet a person could use a stylus or finger to add their signature.  If we use a PC it seemed that using a signature pad (like those from Topaz) would be better than having someone use a mouse.  I was whether or not you knew the widget will work with an external touchpad accepting the signature. 

Thanks, 

Mike 

----- Original Message -----

**Comment by dvdotsenko** [comment]
Re: "using a signature pad (like those from Topaz) would be better than having someone use a mouse" 

Better for whom? 

Having no insight into your business model, deployment scenarios, equipment financing facility, it is tremendously hard to speculate on what would be "better" and for _whom_ it would be better.

If a separate stroke digitizing capture device effectively acts like a mouse (think Intuos tablets) and your capturing surface can be a browser, jSignature will work with such "external signature tablet".
