### ISSUE TITLE
Implement FlashCanvas support for Canvas-less browsers.

### ISSUE THREAD

**Issue by ghost** [willowsystems/jSignature#2]
http://code.google.com/p/flashcanvas/

**Comment by willowsystems** [comment]
Parts:

http://code.google.com/p/flashcanvas/

This may be inefficient 

```
<!--[if lt IE 9]>
<script type="text/javascript" src="path/to/flashcanvas.js"></script>
<![endif]-->
```

Consider:

```
document.createElement("canvas");
window.FlashCanvasOptions = {
    swfPath: "http://example.com/js/"
};
jQuery.getScript("flashcanvas.js", function(){
    ......
});
```

Followed by:

```
var canvas = document.createElement("canvas");
document.getElementById("target").appendChild(canvas);
if (typeof FlashCanvas != "undefined") {
    FlashCanvas.initElement(canvas);
}
```

**Comment by willowsystems** [comment]
swfobject returns version 0.0.0 when no Flash available. 

we need 9+ for FlashCanvas

swfobject.hasFlashPlayerVersion("9")

**Comment by willowsystems** [comment]
likely flow:
1. jSig init: started:
2. Create Canvas tag, check for .getContext
3. If 2 = no
   1. check if Flash is supported, try to install if possible.
   2. Check if / insure FlashCanvas is here
   3. Init FlashCanvas against above Canvas tag.
      7 do other init things

in #4 propose using swfobjct to detect flash (need >=9) and try to install if possible. This is after we already established disfunctional canvas, so all this annoyance will target only broken / old browsers.

Think using jQuery.getScript(fn, callback) 
where callback is picking up init of canvas.

Think loading swfobjct and FlashCanvas in one .min.js file.
