### ISSUE TITLE
Documentation unclear on critical information

### ISSUE THREAD

**Issue by finallyblueskies** [willowsystems/jSignature#68]
Apologies if I'm missing something, but this is the third time I'm using this plugin and the third time I'm having trouble finding documentation on what settings I can pass on jSignature's initialisation. I really feel like it should be much clearer.

**Comment by GeorgeD19** [comment]
I'll write down some here that hopefully will help.

```
settings = {
	'width' : 'ratio' // or int
	,'height' : 'ratio' // or int
	,'sizeRatio': 4 // only used when height = 'ratio'
	,'color' : '#000'
	,'background-color': '#fff'
	,'decor-color': '#eee'
	,'lineWidth' : 0
	,'minFatFingerCompensation' : -10
	,'showUndoButton': false
	,'data': []
};
$("#signature").jSignature(settings);
```

If sizeRatio: 1 then you'd have a box.
