### ISSUE TITLE
Demo doesn't work on IE 8

### ISSUE THREAD

**Issue by gaspowers** [willowsystems/jSignature#7]
Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; BRI/1; InfoPath.3; .NET4.0C; MS-RTC LM 8; BRI/2; MALC)
Timestamp: Wed, 15 Aug 2012 01:58:28 UTC

Message: Unexpected call to method or property access.
Line: 28
Char: 6
Code: 0
URI: http://willowsystems.github.com/jSignature/

Message: Unexpected call to method or property access.
Line: 275
Char: 4
Code: 0
URI: http://willowsystems.github.com/jSignature/

**Comment by dvdotsenko** [comment]
Confirmed for IE8 + Flash v9. 

It's possible the second error is the one causing the issue.

Regular "IE7, IE8 testing I do is within IE9's "IE8" and "IE8" emulation modes, against the latest Flash. There, it works. 

Need to investigate this more.

**Comment by gaspowers** [comment]
Line 1030 in the uncompressed version is where the error occurs:
$(canvas).children('object').get(0).resize(Math.ceil(canvas.width \* zoom), Math.ceil(canvas.height \* zoom))

Removing the above line gets the page to load correctly but I can't seem to get the actual canvas to show up and capture pen strokes. I will continue to look at solving the problem as well.

**Comment by dvdotsenko** [comment]
Demo updated with fixes to jSignature.js, FlashCanvas.js and to the demo-page-specific code.
- `.appendChild` cannot be used on `script` tags in IE.
- `InjectCSS` function now supports IE-specific ways of injecting CSS.
- jSignature no longer infini-loops on init when windowResize-induced redraw is triggered by removal of jSignature on IE
- FlashCanvas.js now does not continue to spin when canvas is gone.

Tested to work on real IE 8, 32bit, Flash v11

**Comment by gaspowers** [comment]
Looks good. However the addition of line 1301 console.log("Initing jSignature") now causes IE 8 to break if the following code block is not defined on the calling web page:
//make it safe to use console.log always
    (function(b) { function c() { } for (var d = "assert,count,debug,dir,dirxml,error,exception,group,groupCollapsed,groupEnd,info,log,timeStamp,profile,profileEnd,time,timeEnd,trace,warn".split(","), a; a = d.pop(); ) { b[a] = b[a] || c } })((function() {try { console.log(); return window.console; } catch (err) {return window.console = {};}})());

**Comment by dvdotsenko** [comment]
Arg!!! Will clean up.

**Comment by dvdotsenko** [comment]
Clean up achieved. :)

Thank you for help.
