### ISSUE TITLE
IE Problems

### ISSUE THREAD

**Issue by arnonate** [willowsystems/jSignature#8]
I cannot get the signature element to show up on IE in any version. I have followed directions thoroughly. Works great in FF, Safari, Chrome. Not IE. Any suggestions?

**Comment by arnonate** [comment]
http://acot.edu/test/ for a reference

**Comment by dvdotsenko** [comment]
Sounds like you have 2 problems:
1. Your html is marked up such that in all IE it loads in Querks mode (old
   IE rendering engine, one without canvas) and
2. You dont load FlashCanvas on IE

We test on IE 8 (flashcanvas), IE9 native canvas before every release

**Comment by dvdotsenko** [comment]
@arnonate Re: test site

I cannot figure out what I would need to be looking at there. On the first 4 pages of the form the signature does not appear anywhere in Chrome. Is it on some other page? Is there a direct link to it?

**Comment by dvdotsenko** [comment]
@arnonate 

Just as a general test, i opened http://acot.edu/test/ in IE8 and IE9, opened console and did this:

```
// uses jQuery to create new `div` element and attach it to end of document.body.
// then inits jSignature on top of that div.
$('<div></div>').appendTo(document.body).jSignature()
```

In both IE 8 and IE 9 this worked. I saw jSignature pad attached to the end of the body and I was able to sign.

So, as of morning of Sunday (US time) you had all the parts loading correctly into the page.
