### ISSUE TITLE
Problem after scrolling on touch devices

### ISSUE THREAD

**Issue by sduivenvoorden** [willowsystems/jSignature#86]
Hello,

I have a problem with the jSignature script on my webpage. It works fine, only on touch devices like ipad, iphone etc. the signature makes stripes after scrolling. I tried several options but all without any result. 

Enabling document.ontouchmove = function(e){ e.preventDefault(); } stops scrolling at all. Thats a problem, the signature is below the page.

Enabling event.preventDefault(); on the Signature divs let me sign a nice signature but after scrolling it doesn't work anymore.

Setting none of these, scrolling the page works fine but touching the signature field, it scrolls the page and results also in a not wanted signature. 

Hopefully someone could help me. thanks in advance!

**Comment by KeithETruesdell** [comment]
This almost sounds like an issue I had where it was being initiated several times with the scrolling or through other means that you may not be aware of.  Are the lines all similar to the "signature line" that you have?  So it looks like there is just 10 signature lines?

**Comment by sduivenvoorden** [comment]
Thanks for your reply. Don't know the solution anymore but fixed it after a while.
